name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy files to VPS
        run: |
          scp -i ~/.ssh/id_rsa -rv ./docs ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/var/www/l8a.dev
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth.sock
